### ISSUE TITLE
Dump service messages

### ISSUE THREAD

**Issue by expectocode** [expectocode/telegram-export#10]
This needs a new table, and the associated dumping code

**Comment by Lonami** [comment]
Shared:
* `id`
* `to_id`
* `from_id`
* `date`
* `out`
* `mentioned`
* `media_unread`
* `silent`
* `post`

Message-specific:
* `message`
* `fwd_from`
* `via_bot_id`
* `reply_to_msg_id`
* `media`
* `reply_markup`
* `entities`
* `views`
* `edit_date`
* `post_author`
* `grouped_id`

MessageAction-specific:
* `action`

**Comment by Lonami** [comment]
Not sure if it deserves its own table or just live with the normal messages… We could simply add an `action` field to the `Message` which, if set, indicated *what* action it is (and then the `message` itself is a JSON representation of the entire action). We can also save `media` like this (e.g., group photo updated so it has to easily show the photo).

**Comment by expectocode** [comment]
I like that idea! Maybe ServiceAction instead of just action though

**Comment by Lonami** [comment]
`action` sounds reasonable enough, because `MessageService` has an `action`. And really, a `Message` that performs an `action`… can only be one thing.

**Comment by expectocode** [comment]
a message with an action could also be interpreted as one of telegram's many interactive bot features. ServiceAction is clearer and not too verbose

**Comment by Lonami** [comment]
> as one of telegram's many interactive bot features.

Those are a whole different story we don't support. It's the [`reply_markup`](https://lonamiwebs.github.io/Telethon/types/reply_markup.html) field, which I have no idea how to nicely dump, or if we should even support. It's a backup. Do you really need to know what the buttons of heaven knows which bot were some years ago…?

**Comment by expectocode** [comment]
My point is not that we would be dumping those but that "action" is a name that doesn't immediately tell you what it's for, whereas ServiceAction is
