### ISSUE TITLE
Can't download any media

### ISSUE THREAD

**Issue by lorenzoromani1983** [expectocode/telegram-export#103]
I'm in a channel with 30+ users and hundreds of .pdf files I want to download.
I configured the config.ini file and running _main_ with the following command:

C:\Users\Lorenzo>python C:\Users\Lorenzo\Anaconda\Lib\site-packages\telegram_export\__main__.py --config-file C:\Users\Lorenzo\Anaconda\Lib\site-packages\telegram_export\config.txt --download-past-media

it does download any file.
if i try without the --download-past-media it gets this error:

AttributeError: 'Document' object has no attribute 'version'

what am i doing wrong?

how back can I go while downloading pdfs posted previously?

**Comment by Lonami** [comment]
> what am i doing wrong?

You need to manually downgrade the version of `telethon` to 1.4.3 by running:
```sh
pip install telethon==1.4.3
```

**Comment by expectocode** [comment]
@lorenzoromani1983 I'm in a channel with 30+ users and hundreds of .pdf files I want to download.

**Comment by expectocode** [comment]
This kind of thing makes me think that we should have some options in telegram-export that would allow it to do less work (eg not getting other messages, or full user info)

**Comment by expectocode** [comment]
Not really related to the issue, just a note on improving the tool.
