### ISSUE TITLE
dumper.py - 'Document' object has no attribute 'thumb'

### ISSUE THREAD

**Issue by ApexLead** [expectocode/telegram-export#105]
Whenever I run the script it creates a database and actually dumps messages for a like a minute, and then crushes with the following error: 
File "/usr/local/lib/python3.6/dist-packages/telegram_export/dumper.py", line 537, in dump_media row['thumbnail_id'] = self.dump_media(doc.thumb)
AttributeError: 'Document' object has no attribute 'thumb'

I dont even need media downloaded, is there a way to ignore / fix it?

**Comment by Lonami** [comment]
Downgrade Telethon to 1.4.3.

**Comment by ApexLead** [comment]
How do I do that?

**Comment by Lonami** [comment]
`pip install telethon==1.4.3`

**Comment by ApexLead** [comment]
Thanks! It made it work for longer, but when it got to 97% it crushes with another error:
File "/usr/local/lib/python3.6/dist-packages/telegram_export/downloader.py", line 507, in start req.offset_date = min(m.date for m in history.messages)
TypeError: '<' not supported between instances of 'NoneType' and 'dateime.datetime'

Any idea how to fix it?

**Comment by ApexLead** [comment]
Sorry didn't want to cause too many problems, added a new issue.
