### ISSUE TITLE
dont know how to start

### ISSUE THREAD

**Issue by SiNk011** [expectocode/telegram-export#109]
Sorry but iam a dumb noob. 

ython and everything is installed but i just dont know where to start and where to type in the groupname where i want to get the users from.

I hope you can help me

**Comment by juanvelascogomez** [comment]
Hello there.

Did you manage to run Telegram Export with your Telegram client by using your own `config.ini`? You will need your phone number, an API ID and an API Hash (you can get those two [here](https://my.telegram.org/auth)) 

In case not, this [usage tutoria](https://github.com/expectocode/telegram-export#usage)l could help you with that.

If you just want to backup information about one particular entity, use `telegram-export --list-dialogs` to get the ID of that entity and then add it in your `config.ini` **whitelist**.

> You might want to take a look at [Telethon](https://github.com/LonamiWebs/Telethon) and the [docs ](https://telethon.readthedocs.io/en/latest/extra/basic/entities.html) about retriving users from an entity.

**Comment by juanvelascogomez** [comment]
Maybe we can close this issue, no answer from @SiNk011.
