### ISSUE TITLE
Dump participant lists

### ISSUE THREAD

**Issue by expectocode** [expectocode/telegram-export#11]
Due to account deletion or service message deletion, users joining and leaving may not appear in the service messages. We should store participants of dialogs, but in a way that does not have massive repetition. Also, it's probably overkill to dump every user who is a participant of any dumped dialog.

These requirements imply some kind of external store using deltas rather than full lists

**Comment by expectocode** [comment]
Not assigning this to 0.1 milestone as it's not a core feature and isn't in history-dump.

**Comment by Lonami** [comment]
Dump users in the user table. Have a table "Participants" with `ContextID` (integer), `Added` (text), `Removed` (text), and `Delta` (boolean). The first time a dump is done, all the IDs are stored in the `Added` field, comma separated, with the `Delta` field set to `0`. Every other time for this chat, `Delta` will be set to `1`, and `Added`/`Removed` set accordingly.

**Comment by Lonami** [comment]
What bothers me the most is that we require `UserFull` to dump users. Groups with thousands of members will take well over 15 minutes just to dump 1,000 people, only to get the bio. Getting a list of 50,000 people shouldn't take more than a minute since flood waits seem to be really low when getting participants, but we lose the bio. Though, it would still be useful to generate the delta.

**Comment by Lonami** [comment]
Actually I'm gonna do this and be done with it.

**Comment by Lonami** [comment]
I just noticed the `Delta` field is stupid. The whole point is to save deltas so besides the first (smallest `DateUpdated` all will be deltas…

**Comment by Lonami** [comment]
👌

**Comment by expectocode** [comment]
I wonder if we could calculate if it would be more efficient to store an absolute list instead of a delta (eg when the entire chat was emptied and new members join) or if this is so unlikely it wouldn't be worth adding support for (complicating schema, too)

**Comment by Lonami** [comment]
One thing we can do is always save initial, deltas, and last state (so the last state doesn't need to be recalculated). Even then, we can just wait and see if that really becomes an issue (I'm sure flood waits are far worse).
