### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by SiNk011** [expectocode/telegram-export#110]
![pyth](https://user-images.githubusercontent.com/47871951/53681071-37546a80-3ce4-11e9-8272-dce8f131b38b.PNG)

**Comment by SiNk011** [comment]
how to solve this

**Comment by juanvelascogomez** [comment]
Use [pip](https://pypi.org/project/pip/). 
For example:  `pip3 install tqdm --upgrade`
Same thing in case you are missing more modules.
