### ISSUE TITLE
How to Group by message by day from Table Message 

### ISSUE THREAD

**Issue by tanoggy** [expectocode/telegram-export#116]
I don't know the data using. Datatypes is INT, how to convert to day. I want to list message day by day

**Comment by expectocode** [comment]
@tanoggy The dates are all in Unix timestamp format, every language should have some tools to convert that into a date which you can work with

**Comment by tanoggy** [comment]
> @tanoggy The dates are all in Unix timestamp format, every language should have some tools to convert that into a date which you can work with

Thank you. I do it
