### ISSUE TITLE
phone banned

### ISSUE THREAD

**Issue by dumpload** [expectocode/telegram-export#117]
run telegram-export ,we  account phone banned. god. baby. my account.i love you

### 
2019-07-08 16:09:17,337 - exporter - INFO - Saving to 
testext/testdown
2019-07-08 16:09:18,362 - telegram_export.downloader - INFO - Done. Retrieving full information about 0 missing entities.
entities: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.07 entities/s, chat=example]
media: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 223k/223k [00:06<00:00, 34.4kB/s, chat=example]
2019-07-08 16:09:26,588 - exporter - INFO - Closing exporter
Telegram Usernames: ?| 0/? [00:00<?, ? messages/s]Traceback (most recent call last):███████████████████████████████████████████████| 1/1 [00:00<00:00,  3.30 entities/s, chat=Telegram Usernames]
 ###

**Comment by hanjackcyw** [comment]
me too. use telegram-export --list-dialogs. my phone was immediately bannned after input authorization code.

**Comment by Lonami** [comment]
See https://github.com/LonamiWebs/Telethon/issues/824 for how to recover the accounts.
