### ISSUE TITLE
Cleaner CLI output using tqdm

### ISSUE THREAD

**Issue by expectocode** [expectocode/telegram-export#12]
Currently the information printed out is quite verbose and inconsistent, and omits important information like the name of the currently dumping dialog. We should improve this. One possibility is https://github.com/tqdm/tqdm for the progress bars

**Comment by juanvelascogomez** [comment]
Hi there. Last week I downloaded this repo and one of the things I added was **tqdm progress bars** for waiting times. I think it would be a great idea to add this feature. If you want, I could contribute with that small piece and maybe contribute with your project in more advanced tasks. 

As I said, Im confident in telegram-export and want to congratulate you both for it.

Great work. Keep going guys.

**Comment by expectocode** [comment]
Thanks! I think we will use tqdm, just working on some other things at the moment. Feel free to join the discussion/dev group for this project t.me/expectocode :)

**Comment by juanvelascogomez** [comment]
Thank you @expectocode !

**Comment by expectocode** [comment]
https://github.com/expectocode/telegram-export/commit/da152185f9b68df7125d2e75419146f680ab671a, we're getting there.
