### ISSUE TITLE
Fix entity dumping resuming

### ISSUE THREAD

**Issue by expectocode** [expectocode/telegram-export#14]
Since we download all messages, then the entities (users, channels etc) from those messages, when the dumping is interrupted those entities are never dumped. This could be solved by dumping entities at the same time as messages, though this may have speed costs.

**Comment by Lonami** [comment]
The method is becoming a monster though. Needs cleaning.

**Comment by Lonami** [comment]
Way better with https://github.com/expectocode/telegram-export/commit/7fc832b117ead5ba8415ccfe2351e0896b305442.
