### ISSUE TITLE
Previously located Media should be downloadable later

### ISSUE THREAD

**Issue by expectocode** [expectocode/telegram-export#19]
As summarised by Lonami:

>i want to be able to dump this chat without media
>and in two years i want to come back and say, "oh man, i need the media"
>but not redownload the same messages

The problem here is knowing what information we need to reliably download media in the future, and presenting a good UX for this operation.

I suggest a Media table column for filename, and a command line flag like `--download-past-media CONTEXT_ID`

**Comment by Lonami** [comment]
If only there was a way to tag media so it could be identifiable later :( might be possible with photos adding some special kind of metadata but things like text files sound much harder.

**Comment by Lonami** [comment]
I can also dump the filename *when dumping the media*, so when we're going to download that file it will always point to the same file. This is definitely less flexible, though >:(

**Comment by Lonami** [comment]
Needs a nice console argument though.
