### ISSUE TITLE
Whitelist/blacklist comments per ID

### ISSUE THREAD

**Issue by expectocode** [expectocode/telegram-export#21]
Since we require a username, phone number, or context ID for the whitelist and blacklist, it would be nice if users were able to leave a comment by each item to remember what context that ID is for. As far as I know, there isn't an easy way to do this with INI - comments are for the whole line. Perhaps we could parse comments in the list ourselves.

**Comment by Lonami** [comment]
Uhm, I would rather we could separate IDs with a colon maybe? So you did:
```ini
Whitelist = 123: My friend, 456: My dog
```

**Comment by expectocode** [comment]
Colon for comments sounds as good as anything, i'll implement this now

**Comment by expectocode** [comment]
75623119843d7e2dc525dc09fae536772c5094b7

**Comment by Lonami** [comment]
Well that was fast.
