### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Lonami** [expectocode/telegram-export#25]
From #24:

```
/usr/local/lib/python3.6/dist-packages/telethon/telegram_client.py:291: RuntimeWarning: coroutine 'TelegramClient._check_events_pending_resolve' was never awaited
self._check_events_pending_resolve()
2018-03-03 22:26:51,842 - main - INFO - Closing exporter
example: 0 messages [00:00, ? messages/s]Traceback (most recent call last):██████████████████████████████████████████████| 1/1 [00:00/00:00, 9.94 entities/s, chat=example]
File "telegram_export.py", line 289, in
ret = loop.run_until_complete(main())
File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
return future.result()
File "telegram_export.py", line 263, in main
await downloader.start(who)
File "/video/backup_telegram/telegram-export/downloader.py", line 420, in start
max_id = self.dumper.get_message_id(target_id, 'MAX')
File "/video/backup_telegram/telegram-export/dumper.py", line 591, in get_message_id
""".format(which=which), (context_id,)).fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Lonami** [comment]
@nobody16 I do get:
```
/usr/local/lib/python3.6/dist-packages/telethon/telegram_client.py:291: RuntimeWarning: coroutine 'TelegramClient._check_events_pending_resolve' was never awaited
self._check_events_pending_resolve()
```

But I cannot trigger the `TypeError`. Were you trying to dump a channel, chat, user…?

**Comment by nobody16** [comment]
python3 telegram_export.py --list-dialogs

/usr/local/lib/python3.6/dist-packages/telethon/telegram_client.py:291: RuntimeWarning: coroutine 'TelegramClient._check_events_pending_resolve' was never awaited
  self._check_events_pending_resolve()
<coroutine object list_or_search_dialogs at 0x7f0081198db0>
sys:1: RuntimeWarning: coroutine 'list_or_search_dialogs' was never awaited

Trying to do with "Blacklist" in config.ini
Blacklist = +34600123123
/usr/local/lib/python3.6/dist-packages/telethon/telegram_client.py:291: RuntimeWarning: coroutine 'TelegramClient._check_events_pending_resolve' was never awaited
  self._check_events_pending_resolve()
2018-03-03 23:36:22,693 - __main__ - INFO - Closing exporter
Traceback (most recent call last):
  File "telegram_export.py", line 289, in <module>
    ret = loop.run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "telegram_export.py", line 268, in main
    avoid = set(utils.get_peer_id(x) async for x in entities)
TypeError: 'async_generator' object is not iterable

**Comment by expectocode** [comment]
@Lonami the TypeError is in get_message_id if nothing was retrieved from the DB when trying to get the max or min message ID.

As for the async_generator error and a couple of other bugs, i've fixed those in d8fb14bd2ec5e2cdb7408ca50f603ee19be432e9

**Comment by Lonami** [comment]
> if nothing was retrieved from the DB when trying to get the max or min message ID.

That's true. However I just tried deleting the database (so it would be empty) assuming the method would be called and fail but it didn't fail so I'm not sure under which conditions he had triggered the issue.

**Comment by expectocode** [comment]
In any case, we should handle such a case instead of raising a confusing error.

**Comment by expectocode** [comment]
3e4ece2 should fix the TypeError there - it seems it would only happen if no messages had been dumped, ie there was nothing in the chat at all. Very strange.

**Comment by Lonami** [comment]
You could have closed considering https://github.com/expectocode/telegram-export/commit/3e4ece25f746de87fbb16cc90bffc83e7ab33f8c does fix the error (with my further follow-up https://github.com/expectocode/telegram-export/commit/1abb9b3daa978bc8cf37004b2a633ba6b37a8b7d to de-generalize the method and remove exceptions).
