### ISSUE TITLE
Speed problems

### ISSUE THREAD

**Issue by nobody16** [expectocode/telegram-export#29]
Finally I have it running! after some closed bugs (thanks!).

... but, I have huge connection and I see 180kb/s speed  limitation downloading some Documents (700Mb file). It's strange, using other tools I  got more speed, maybe its a API limitation? maybe its a telethon limitation?

**Comment by expectocode** [comment]
or maybe `pip install --user --upgrade cryptg`, to be more specfic

**Comment by nobody16** [comment]
Yep, now its 2Mb/s so, you are right again.
maybe should be in the installation notes ;)
Danke.

**Comment by Lonami** [comment]
Surprised the speedup is this huge ;) we can leave this open until the `README.md` is updated.

**Comment by expectocode** [comment]
@nobody16 Good to hear! I'll update the readme

**Comment by expectocode** [comment]
aea7cd7

**Comment by expectocode** [comment]
PS it's worth noting that the speed you're getting is likely limited by Telegram and not by the crypto library
