### ISSUE TITLE
Download all profile pictures 

### ISSUE THREAD

**Issue by pielco11** [expectocode/telegram-export#37]
Now as now telegram-export downloads only the current propic, I think that it would be nice to get every propic that is possible to see as like as in the apps.

**Comment by Lonami** [comment]
It should just be matter of using [`GetUserPhotosRequest`](https://lonamiwebs.github.io/Telethon/methods/photos/get_user_photos.html) somewhere, and probably [`InputMessagesFilterChatPhotos`](https://lonamiwebs.github.io/Telethon/constructors/input_messages_filter_chat_photos.html) for chats (never tried, not sure).

**Comment by expectocode** [comment]
This would require a rework of the DB schema, and I'm not really convinced that it's very useful. It would definitely improve completeness though

**Comment by pielco11** [comment]
Closing because the feature it's not mandatory and requires a rework of the db, might reopen in the future
