### ISSUE TITLE
Proxy support in telegram-export

### ISSUE THREAD

**Issue by nkonin** [expectocode/telegram-export#44]
It would be nice to have ability to use proxy and set credentials from config.ini / command-line params.

**Comment by expectocode** [comment]
@nkonin I agree, this would be nice. I have quite a lot of things to do at the moment, is this something you need soon?

**Comment by nkonin** [comment]
@expectocode for current moment I can't use your project without proxy (Russian government blocks Telegram). But I think I can do this feature by myself and then open PR.

**Comment by expectocode** [comment]
@nkonin Go for it :D and feel free to ask for advice in the group

**Comment by nkonin** [comment]
@expectocode You mean there is a telegram group around this project?

**Comment by expectocode** [comment]
@nkonin yep, group username is my github username

**Comment by expectocode** [comment]
1e13a2d
