### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [expectocode/telegram-export#49]
Greetings @expectocode  ,

I was passing by (this repository) and tought I'd like to collaborate by proposing a logo
if that's something that may interest you! let me know!

I'm a Graphic Designer and an Open Source enthusiastic
looking to improve my portfolio and collaborate to really cool projects like this one!

Best Regards,
-Luigi.

**Comment by Lonami** [comment]
@LuigiBaute tfw no logo for telethon

**Comment by expectocode** [comment]
Yes, that would be wonderful! I'd love to see your "first draft"

**Comment by LuigiBaute** [comment]
Great @expectocode ,

Before proceeding towards the logo-making process I'll give you some questions that would help _us_ create a wonderful logo that suits this project best.

What's the name that should be displayed on the logo/icon ?

What's the purpose/goal of this project ? (details of the project can work too)

What's the message you would like the logo/icon to transmit?

I'll be looking forward to your reply! hopefully something good can come out of this work!

**Comment by expectocode** [comment]
The name is telegram-export, or just export.

The goal is to download your Telegram chats and data to a database for permanent storage (in case of some deletion mistake) and to have fun with using the data for analysis, making graphs etc.

The message is I guess about downloading and saving all this stuff

**Comment by LuigiBaute** [comment]
Hello! @expectocode  this is my first proposal, it can be in any color you want it, i'd like to hear any suggestion +1
![propuesta 1](https://user-images.githubusercontent.com/36426974/41241469-fd1b5656-6d6a-11e8-89c0-0e379573c9d6.png)

**Comment by Lonami** [comment]
*(opinion ahead)* the first four look like a bit of an angry cloud, with the V shape and the pointy bits. In general, it looks more like a shopping cart than a download arrow as well.

Also note that the project is `telegram-export` and **not** `telegrama-export`!

**Comment by LuigiBaute** [comment]
Thanks for the feedback, I'll make some adjustments and upload the next proposal when ready @Lonami .

**Comment by LuigiBaute** [comment]
@Lonami  i have updating the logo.
![propuesta 2](https://user-images.githubusercontent.com/36426974/41259635-4a17a414-6da2-11e8-8e18-73d63f2ca615.png)

**Comment by LuigiBaute** [comment]
Hey @Lonami @expectocode 
I have deleted the angry looking face haha.
also fixed the typo, I apologyze for that.
this is what I came up with!
![propuesta 2 1](https://user-images.githubusercontent.com/36426974/41268867-1ffd6c58-6dd0-11e8-927c-a992fd663c73.png)

**Comment by Lonami** [comment]
7 and 8 look the most appealing to me. I would personally add some extra padding around the letters, though, and maybe a little less padding with the outer background in 8.

**Comment by expectocode** [comment]
(opinions) Agreed - 7 is promising. I like icons with slightly abstract geometric designs with few colours, but also I wouldn't want an icon that looks like a phone app (like 5 or 6).

**Comment by LuigiBaute** [comment]
Great Im glad you liked it! @expectocode @Lonami ,
should I present a new proposal with the 7 and 8 scheme?
I could gladly make any adjustment.
I'll look forward for your feedback!

**Comment by Lonami** [comment]
Yes, feel free to make another proposal if you're still up to the task, maybe tweaking 7 as we said a bit.

**Comment by LuigiBaute** [comment]
Hi @Lonami   @expectocode ,
this is what I came up with!
![3 3](https://user-images.githubusercontent.com/36426974/41372307-ea1aa8f2-6f1a-11e8-9cb5-8421df98a983.png)

**Comment by mkellerman** [comment]
I would recommend incorporating the telegram paper airplane logo, and a Database logo.

https://www.flaticon.com/free-icon/telegram-logo_87413
https://www.flaticon.com/free-icon/database_149206

**Comment by Lonami** [comment]
I like the first one the most, with little colours and simple. Still, I would [add some padding](https://github.com/expectocode/telegram-export/issues/49#issuecomment-396494848) to the TE letters.

**Comment by LuigiBaute** [comment]
![4](https://user-images.githubusercontent.com/36426974/41386270-a0cf6d20-6f4e-11e8-91e1-a0bd77df00a0.png)
@expectocode @Lonami

**Comment by Lonami** [comment]
@LuigiBaute the 4 (one with TE in white) is the best, but you're ignoring my suggestion… 😅

**Comment by expectocode** [comment]
Since it seems that @LuigiBaute is no longer updating this thread, I'm happy to switch to using number 4. @Lonami what do you think?

**Comment by Lonami** [comment]
Looks good enough for me. We can use it if you think it's right.

**Comment by expectocode** [comment]
Done
