### ISSUE TITLE
New Feature: export only new entities after [date]

### ISSUE THREAD

**Issue by mkellerman** [expectocode/telegram-export#53]
Exporting some channels may take forever if they have a lot of history. But all you want is x latest posts, or since x number of days.

adding a command line option would help:
telegram_export --since-date '27-06-2018'

or something like this.

**Comment by Lonami** [comment]
There's a problem with this, and it's resuming. Resuming is a very delicate process and having (semi) arbitrary limits like a date only complicates things, at least for now.

**Comment by mkellerman** [comment]
Using MaxChunks did the trick. Allows you to get the latest X number of chunks.
