### ISSUE TITLE
error when run telegram-export

### ISSUE THREAD

**Issue by vhdm** [expectocode/telegram-export#55]
hi, i can't run telegram-export in Centos7, please help

![error](https://user-images.githubusercontent.com/14149777/41254902-1c02c800-6dda-11e8-9441-1fa2d92c648e.png)

**Comment by Lonami** [comment]
Seems like the version table got created but nothing actually added. Is this the first run? Can you try removing the database file? Did some other error occur on the initial run that created the database? Here's the relevant code:
https://github.com/expectocode/telegram-export/blob/d5c33cea8a2c4ff5276dac43c30e2dfc00fbff15/telegram_export/dumper.py#L84-L90

**Comment by vhdm** [comment]
yes this is first run, where is database file? yes error occur on the initial run

**Comment by Lonami** [comment]
The file should be called `export.db` by default on your working directory. Does such file exist?:
https://github.com/expectocode/telegram-export/blob/d5c33cea8a2c4ff5276dac43c30e2dfc00fbff15/config.ini.example#L76

**Comment by vhdm** [comment]
i install telegram-export with "sudo pip3 install --upgrade telegram_export" command and i can't find export.db

**Comment by Lonami** [comment]
Hm… I wonder if somehow due to the lack of permissions when running export created the file but couldn't write…? Not sure, right now, sorry.

**Comment by Lonami** [comment]
Where was this file?

**Comment by vhdm** [comment]
/root/.config/export.db

**Comment by Lonami** [comment]
Can you test this patch?:
```sh
sudo pip3 install --upgrade git+https://github.com/expectocode/telegram-export@master
```

**Comment by vhdm** [comment]
![screenshot from 2018-06-12 15-26-42](https://user-images.githubusercontent.com/14149777/41286570-302d6742-6e55-11e8-994b-96e292e19470.png)

**Comment by Lonami** [comment]
Oops! That's what happens when you edit code from GitHub…

**Comment by Lonami** [comment]
[Try again](https://github.com/expectocode/telegram-export/commit/d4e4b674dd6a91644f8bdbf2d1d2642084ea30e0)?

**Comment by vhdm** [comment]
this step?
sudo pip3 install --upgrade git+https://github.com/expectocode/telegram-export@master

**Comment by Lonami** [comment]
@vhdm yes.

**Comment by vhdm** [comment]
![screenshot from 2018-06-12 15-32-05](https://user-images.githubusercontent.com/14149777/41286746-cc7632b4-6e55-11e8-8524-5d7bb590454b.png)

**Comment by Lonami** [comment]
@vhdm are you sure you're running just one instance of export? Seems like it wasn't closed properly before…

**Comment by vhdm** [comment]
wait to restart system and try again

**Comment by vhdm** [comment]
thnaksssssss, worked
![screenshot from 2018-06-12 15-39-33](https://user-images.githubusercontent.com/14149777/41287087-e32a304a-6e56-11e8-8590-15ec94058052.png)

**Comment by Lonami** [comment]
Nice to hear. Enjoy the program and please report any other issues you encounter :)
