### ISSUE TITLE
Bad Interpreter : Python No such File or Directory

### ISSUE THREAD

**Issue by vhdm** [expectocode/telegram-export#56]
@Lonami 
hi, unfortunately, I still error after reinstall ubuntu
![screenshot from 2018-06-13 03-06-03](https://user-images.githubusercontent.com/14149777/41345006-c01a2792-6f17-11e8-86f1-41a878030628.png)

**Comment by expectocode** [comment]
@vhdm Sorry about that, it's a known bug. Until we fix it, the fix is to edit the first line of that file to say the correct path to your python3

**Comment by vhdm** [comment]
@expectocode 
thank you,
![screenshot from 2018-06-13 03-45-18](https://user-images.githubusercontent.com/14149777/41346710-a9249b3a-6f1c-11e8-84a1-1491b1d39272.png)

**Comment by Lonami** [comment]
https://github.com/expectocode/telegram-export/commit/269fcae7e63cfe05d2e188b7c5f6d484a3f31aec should have fixed this issue. If it hasn't please reopen.
