### ISSUE TITLE
JSON-based ElasticSearch tool 

### ISSUE THREAD

**Issue by pielco11** [expectocode/telegram-export#6]
I think that could be useful, and more easy to handle with, the `json` type format for dumping/report/storage. What about this?

**Comment by Lonami** [comment]
No, dumping a million messages into a JSON file is not a good idea. Files need to be stored separately anyway. SQLite is a good choice which is not hard to upgrade when necessary. It's reliable, fast and builtin. Definitely the best way to query for anything. This doesn't stop us from adding a formatter output to JSON, if the user wants to further analyse the data.

**Comment by expectocode** [comment]
The structure of the code would allow for dumper.py to be switched out for a JSON dumper, although the methods it would be expected to implement are designed around the idea of a relational store. Also, the whole point of this project is to dump into a database rather than json files as in history-dumper.

**Comment by expectocode** [comment]
We do have plans to implement some formatters which would extract data from the database and display it in different forms, and JSON could definitely be involved there.

**Comment by pielco11** [comment]
@Lonami well, the json dump will be in memory and just for a short time... to be indexed to elasticsearch.
Indexes are far far faster than databases, with mysql I reach ~200 items/s while with indexes I reach ~5000 items/s. There's a reason if S.E. use indexes and not dbs, that's why I'd like a json report.

**Comment by Lonami** [comment]
What are those times for exactly? Either way… after sime discussion we decided SQLite would be a good option instead of just dumping everything as JSON, which would be trivial. Nothing stops us from just doing `.to_dict()` and sanitizing the dictionaries, prior to dumping the raw response data from the server (MongoDB would just take the dictionaries and be done with it!). I was unaware of elasticsearch and such amazing speeds when this project started, and my previous attempts at dumping the raw responses binary serialized yielded horrible times (so I didn't expect JSON to be any better).

**Comment by Lonami** [comment]
Not trying to argue, just asking since we talked quite a bit before making this decision :P

**Comment by pielco11** [comment]
I agree with the facts that json is not as good as db to store infos, but with a single line of code you can post a json report to the index in elasticsearch. So the reason why I'm asking for a json report is just to handle easily with elasticsearch.

With ES you can do a lot of amazing stuff, and that histogram is just the beginning. For example with a couple of seconds you can get the firsts top 5 biggest channels, or more active chats in a specific time range.

![immagine](https://user-images.githubusercontent.com/17363750/36635512-acec0e9e-19b6-11e8-80d3-d7bd98d99892.png)

PS: about times, sorry my bad for a not good explanation. Those times are "numbers of items loaded in the db" and "numbers of items indexed in elasticsearch index" respectively.

**Comment by expectocode** [comment]
It's now possible to extract users, supergroups, channels, chats, and messages from the database like this:

`>>> from base_formatter import BaseFormatter`
`>>> formatter = BaseFormatter('export.db')`
`>>> formatter.get_user(190601014)`
`User(id=190601014, date_updated=1519517636, first_name='LikeBot', last_name=None, username='like', phone=None, bio='A cool bot to create posts with emoji-based like buttons.', bot=1, common_chats_count=0, picture_id=6648)`
`>>> import json`
`>>> json.dumps(formatter.get_user(190601014)._asdict())`
`'{"id": 190601014, "date_updated": 1519517636, "first_name": "LikeBot", "last_name": null, "username": "like", "phone": null, "bio": "A cool bot to create posts with emoji-based like buttons.", "bot": 1, "common_chats_count": 0, "picture_id": 6648}'`

Does this fit what you were looking for?

**Comment by expectocode** [comment]
By the way @pielco11 is your visualisation code public? I was going to rewrite telegram-analysis to work with telegram-export, but it looks like you may have already done something similar. Perhaps we could work together?

**Comment by pielco11** [comment]
@expectocode sorry for the late response (11 hours ago was 01:35 A.M so quite late for my timezone), the dumps looks great, another question: what are all possibles fields for a json dump? I (we) really need this to create an index (we could use dynamic indexes, nested datatype, but I don't think that we really need this).

I would really like to work together.

**Comment by expectocode** [comment]
The fields in the json dump will be the same as the database fields, which are in the readme. You can also see them in the top few lines of base_formatter.py (this is what will actually go into the JSON, and the DB might have extra fields that aren't yet in base_formatter). I don't really understand the ElasticSearch stuff to be honest, so I don't know what you mean by dynamic indexes etc

**Comment by expectocode** [comment]
e17ab18b1cfe0a8cde1d1be532ecb8e238ce3fd3 changes this functionality slightly -- Messages now have the additional fields 'from_user', 'context', and 'reply_message', which are namedtuples themselves. This makes the keys nested, sometimes quite heavily if there are a lot of replies. Also, the change from UTC timestamps to UTC datetimes makes the namedtuples no longer JSON serializable, so you may want to write something to convert from datetimes into something serializable.

**Comment by pielco11** [comment]
No problem, thank you for pointing out. Is there a vision of the "final version" for the database? I can do indexes every day, for me it's not a problem, the problem (IMHO) is that people have to "re-dump" messages, chats, whatsoever... and so re-index stuff. Usually I don't play with dbs but, is there a way to "update" them instead? So that if the db structure changes, the entries of the db will be "re-organized" and the data in the index "re-indexed".

**Comment by expectocode** [comment]
Yep, once the schema stops changing so much and gets stable we should only need to change it when Telegram changes something. At this point upgrades will be supported and we'll keep track of versions using the Version table (there is already code for this)

**Comment by expectocode** [comment]
When #20 gets merged, I'll close this.
