### ISSUE TITLE
better date formating

### ISSUE THREAD

**Issue by gozes** [expectocode/telegram-export#60]
in the database the dates are formatted as something like 1529956521

it would be nice to have a proper date in there. any date format will do just something more human readable

**Comment by expectocode** [comment]
@gozes The database isn't really intended to be human readable, sorry

**Comment by Lonami** [comment]
@gozes you can use `datetime.fromutctimestamp(x)` to get a human readale version from Python.

**Comment by gozes** [comment]
@expectocode  I don't mean the full database  but just the date field on the messages table would be nice

**Comment by Lonami** [comment]
@gozes but having an integer to save the date is much easier to work with from a programming point of view. SQLite doesn't even have a type for dates, and saving their unix timestamp is a sane thing to do.

**Comment by gozes** [comment]
@Lonami agree it make sens if you are working with telethon  from your own python code. However, in this case this is an export tool so it would make more sens, at less to me, to have  both unix time and  human readable dates because in the use case of this tool 90% of the time when using this tool you just want to export some messages for whatever reason and be done. If you need something more then that when you would break out your own script

**Comment by Lonami** [comment]
@gozes that's duplicating information then, why keep a separate human-readable field when you can simply run `datetime.utcfromtimestamp()`?

**Comment by expectocode** [comment]
@gozes We're developing this with the intended usage being a quick script to analyse the data (i do plan on releasing some common code for extraction)

**Comment by gozes** [comment]
@Lonami because in my case I just run it from the command line and then use the go in to the sqlite db and exported the messages table to a csv.

**Comment by expectocode** [comment]
Sorry, we don't currently plan to do this.
