### ISSUE TITLE
How to download likes as well?

### ISSUE THREAD

**Issue by gogainda** [expectocode/telegram-export#64]
Generated with LikeBot

**Comment by expectocode** [comment]
Sorry, this isn't supported.

**Comment by Lonami** [comment]
Perhaps we should reconsider whether it's useful information or not?

**Comment by expectocode** [comment]
Yeah, I could see people wanting to save it. We could have a JSON column in Message for button data, or maybe a Button table with a button index or coordinate, and a ContextID/MessageID foreign key

**Comment by Lonami** [comment]
Using JSON for message entities was a bad idea I regret. We're using SQLite exactly to avoid that…

**Comment by Lonami** [comment]
Easier, but not better. Just like Telegram's export feature that gives you JSON, and good luck figuring out what each row would have…

**Comment by secsilm** [comment]
Hi guys, is there any progress on this?

**Comment by Lonami** [comment]
Not really, no.
