### ISSUE TITLE
Adding 2FA password to config file

### ISSUE THREAD

**Issue by juanvelascogomez** [expectocode/telegram-export#67]
It could be interesting to add the possibility of having a 2FA (Second Factor Auth Password) field in the `config.ini `file in order to avoid user interaction with console prompt.

> NOTE: This error has already been transmitted through the Telegram group.
> NOTE: Working on it. I hope to do pull request in a few hours.

**Comment by expectocode** [comment]
Fixed thanks to your PR :)
