### ISSUE TITLE
No such table: SelfInformation

### ISSUE THREAD

**Issue by pielco11** [expectocode/telegram-export#7]
Having this:
```:python
Traceback (most recent call last):
  File "telegram-export.py", line 113, in <module>
    main()
  File "telegram-export.py", line 80, in main
    (client.get_me(input_peer=True).user_id,))
sqlite3.OperationalError: no such table: SelfInformation
```

**Comment by expectocode** [comment]
We recently changed the schema to include a new table, and added a column for pinned messages. As the project is still pre-release, we aren't writing upgrade paths for every change we make yet :/ Sorry. You could alter your tables yourself or make a new database.

**Comment by pielco11** [comment]
Thanks, deleting the database solved the problem.
