### ISSUE TITLE
Display exported data like web telegram.

### ISSUE THREAD

**Issue by Quang-NA** [expectocode/telegram-export#72]
Firstly, Thank you for the great project.
I'm new in the database field. So, someone shows me how to present it like in web telegram.
I really appreciate your support.

**Comment by Lonami** [comment]
> So, someone shows me how to present it like in web telegram.

You should try to word this differently next time. It sounds a bit like an order ;)

[The code](https://github.com/expectocode/telegram-export/blob/master/telegram_export/dumper.py) shows how the data is added to the database and also has the SQL definitions. With that you can know how the data looks like. Once you know how to work with the saved data, you need to make an UI for it. I'm not much of a web guy, so I can't assist any further. There are plenty of resources online to get a basic understanding of SQL and Sqlite in Python, writing about it here would be a waste of time.

**Comment by Lonami** [comment]
Oops, completely forgot about the `--format html` export feature. It's true you could make that one look like Telegram web although it wasn't originally intended. If your friend or you are able to create a nice looking exported HTML, feel free to submit a pull request.

**Comment by expectocode** [comment]
Yes, I would also love to see your friend's code for formatting this. It's something I've been meaning to do myself

**Comment by expectocode** [comment]
However, this isn't a telegram-export issue anymore, so I'm closing it.
