### ISSUE TITLE
 TypeError: 'coroutine' object is not iterable

### ISSUE THREAD

**Issue by CesMak** [expectocode/telegram-export#77]
I currently have this error:

```
Traceback (most recent call last):
  File "multi_img.py", line 16, in <module>
    for message in client.get_messages('me', limit=150):
TypeError: 'coroutine' object is not iterable
```

any help for this?

My code is simple:
from telethon import TelegramClient
api_id=
api_hash=''
client = TelegramClient('test_session', api_id, api_hash)
client.start()
for message in client.get_messages('me', limit=150):
    client.download_media(message)

**Comment by expectocode** [comment]
This isn't an issue in telegram export, you've opened this in the wrong place. Your real problem is that you need to learn about async functions in python, since Telethon uses those.

**Comment by Lonami** [comment]
I wish we had a RTFM label here.

**Comment by expectocode** [comment]
@Knuckl3head Yes, our replies were unhelpful. This is the wrong place for questions about Telethon usage.
