### ISSUE TITLE
CommonChatsCount:OK!- CommontChatsContextID: ?

### ISSUE THREAD

**Issue by Ehishere** [expectocode/telegram-export#80]
Hi,
I think it worth to export CommontChatsContextID (or group name) in addition to the count for commonchats,

Thanks to this great work, I experimented, and for example, 605 users had at least 2 common groups(chat) with the user I used for exporting, many have 4 or 5 and since they are a lurker in some groups, I may need to manually check the common groups for each user from their user info. It might be interesting to know what are those common groups,.. How do you see this?

**Comment by Ehsanmd70** [comment]
Is there a way to find who is an admin?
For example in a group with 3000 members can we say who are the 15 admins of the group?

**Comment by expectocode** [comment]
> Is there a way to find who is an admin? using the exported data?

I don't think that information is saved, sorry.

> I think it worth to export CommontChatsContextID 
Yeah, I see how that would be useful. It's not supplied by the telegram API, so we would figure it out using the database. This could also be done by any external analysis application, using ChatParticipants and seeing which chats you had in common with someone at a given time

> Who are the users in the user table? 

They can be from forwards, too
