### ISSUE TITLE
UnicodeError

### ISSUE THREAD

**Issue by MyPod** [expectocode/telegram-export#83]
First of all, thanks for developing this.

I'm currently having an issue and I don't see any issue, open or past, that is similar, so I opened this one; I'd appreciate pointers in case it's not telegram-export at fault.

I'm running `telegram-export --list-dialogs` and I get the following error after a few lines of output. The OS in use is Debian Stretch, using python3

```Traceback (most recent call last):
  File "/home/user/.local/bin/telegram-export", line 3, in <module>
    runpy.run_module("telegram_export", run_name="__main__", alter_sys=True)
  File "/usr/lib/python3.5/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/lib/python3.5/site-packages/telegram_export/__main__.py", line 316, in <module>
    ret = loop.run_until_complete(main(loop)) or 0
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/user/.local/lib/python3.5/site-packages/telegram_export/__main__.py", line 292, in main
    return await list_or_search_dialogs(args, client)
  File "/home/user/.local/lib/python3.5/site-packages/telegram_export/__main__.py", line 225, in list_or_search_dialogs
    print(fmt_dialog(dialog, id_pad, username_pad))
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f43a' in position 42: ordinal not in range(128)

**Comment by Lonami** [comment]
This is an issue with your terminal, which does not support `utf-8`, so printing some characters fails (probably some of your dialogs have emoji or non-ascii characters on their names).

**Comment by Lonami** [comment]
We can use [this](https://github.com/LonamiWebs/Telethon/blob/92c9bb12b70f28b11abaaa06dca76b13a40db0fe/telethon_examples/interactive_telegram_client.py#L16-L23) though:

```python3

def sprint(string, *args, **kwargs):
    """Safe Print (handle UnicodeEncodeErrors on some terminals)"""
    try:
        print(string, *args, **kwargs)
    except UnicodeEncodeError:
        string = string.encode('utf-8', errors='ignore')\
                       .decode('ascii', errors='ignore')
        print(string, *args, **kwargs)
```

**Comment by expectocode** [comment]
We could even redefine print to the above code, so we don't have to worry about replacing "print" with "sprint" everywhere

**Comment by Lonami** [comment]
Yes, it's possible to `setattr(__builtins__, 'print', new)`, although for that we better handle all `*args`.

**Comment by MyPod** [comment]
I've found the root of the issue in my changing of laptops, with the newer one I used not exporting LC_* environment variables for ssh sessions. This had been masked by my usage of `screen` in the remote system running telegram-export, which kept the program working until a reboot and a new screen session had been launched.

**Comment by expectocode** [comment]
Interesting bug, thanks for the update and glad it works for you now!

**Comment by Lonami** [comment]
While it works for him maybe we should work around it for others. Should we reopen?
